#30 Unsuspend a user from failed logon attempts
infamousjoeg/cybr-cli pull request #43
Opened 2021-01-14 03:19 UTC by AndrewCopeland

2021-01-14 03:27 UTC, AndrewCopeland commented
Having issues with the testing environment. I will inform you when a review is required.

2021-01-14 19:09 UTC, AndrewCopeland commented
The v2 endpoint expects the `UserID` as a number rather than the username. I am thinking about using the old endpoint so its easier and more intuitive for the CLI user to just provide a username.

2021-01-15 02:33 UTC, infamousjoeg commented
> The v2 endpoint expects the `UserID` as a number rather than the username. I am thinking about using the old endpoint so its easier and more intuitive for the CLI user to just provide a username.

I believe that using the older endpoint is okay in this case.  There weren't any _real_ changes otherwise between the two than that annoying change to UserIDs...

2021-01-15 15:19 UTC, AndrewCopeland commented
Tested successfully via the API and CLI. You can review now

2021-01-15 17:43 UTC, infamousjoeg requested changes

2021-01-15 17:43 UTC, infamousjoeg commented on cmd/users.go
> +		fmt.Printf("Successfully unsuspended user'%s'\n", Username)
Prints to STDOUT as `Successfully unsuspended user'cartman'` -- please add a space between `user'%s'`

2021-01-15 17:47 UTC, infamousjoeg approved these changes

2021-01-15 17:51 UTC, merged